### ISSUE TITLE
changing channel frequency

### ISSUE THREAD

**Issue by Technikte** [mulbc/fritzdocsis#11]
Hi,
some beta versions ago I noticed that sometimtes channel "drift" a bit and then the scraper gets a new instead of "following the old one..
like 37.200 MHz and 37.201 MHz, that causes to create more channel then there even exits..for that screenshot it would be normally 5 Upstream Channels
This problem is more or less caused by the fritzbox but there is nothing we can do about that, so only at scraping we can "fix" this behavior.

EDIT: I am running a FB6660 with 7.39-99494 BETA

Solution:
Round the channel freq to one point after comma or just remove the last two digist from the string

example
![grafik](https://user-images.githubusercontent.com/49494924/188330263-77daaf87-7c60-4d76-95e1-51f6981ac08a.png)

**Comment by mulbc** [comment]
what's the query you use on this chart?

**Comment by Technikte** [comment]
![grafik](https://user-images.githubusercontent.com/49494924/188454349-6cd61184-18a1-40b4-a156-b8c5b195876b.png)

**Comment by mulbc** [comment]
Looks like this is _yet again_ a new feature of the beta build ;)
In my stable build, the frequency is an int and doesn't change.

I don't think removing the precision in the exporter is the way to go, since sometimes you might want to have that info (maybe to precisely look at that drift)

What I could offer though is that we split out the frequency at the dot. Leave the first part in the `frequency` label and put the remainder in a new label (`frequency_minor`?)

That way my current parse:

fritz_channel_connection_type{... ,frequency="51"}

would change into:

fritz_channel_connection_type{... ,frequency="51",frequency_minor="0"}

and your

fritz_channel_connection_type{... ,frequency="51.123"}

would change into

fritz_channel_connection_type{... ,frequency="51",frequency_minor="123"}

**Comment by Technikte** [comment]
That would be an option too, in any way we should avoid to "create" an other entry when the frequency drifts..which nevertheless in docsis not really possible/should not be possible.
